name: flutter_dialog_helper
description: Flutter package that allows you to show very simple dialogs with a single line
version: 0.1.1
repository: https://github.com/gerardo-m/flutter_dialog_helper

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
